---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    ignore:
      - dependency-name: "lodash:*"
        # Ignore versions of Lodash that are equal to or greater than 1.0.0
        versions: [ ">=1.0.0" ]
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
